################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/

monitor= ,highres, auto, 2

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, exec, workspace 1
bind = $mainMod, 2, exec, workspace 2
bind = $mainMod, 3, exec, workspace 3
bind = $mainMod, 4, exec, workspace 4
bind = $mainMod, 5, exec, workspace 5
bind = $mainMod, 6, exec, workspace 6
bind = $mainMod, 7, exec, workspace 7
bind = $mainMod, 8, exec, workspace 8
bind = $mainMod, 9, exec, workspace 9
bind = $mainMod, 0, exec, workspace 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, exec, move 1
bind = $mainMod SHIFT, 2, exec, move 2
bind = $mainMod SHIFT, 3, exec, move 3
bind = $mainMod SHIFT, 4, exec, move 4
bind = $mainMod SHIFT, 5, exec, move 5
bind = $mainMod SHIFT, 6, exec, move 6
bind = $mainMod SHIFT, 7, exec, move 7
bind = $mainMod SHIFT, 8, exec, move 8
bind = $mainMod SHIFT, 9, exec, move 9
bind = $mainMod SHIFT, 0, exec, move 10