################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/

monitor= , highres, auto, 2

env = GDK_SCALE,1
env = GDK_DPI_SCALE,1
env = QT_SCALE_FACTOR,2
