preload = ~/pictures/wallpapers/minecraft-1.jpg
preload = ~/pictures/wallpapers/minecraft-2.jpg
wallpaper = HDMI-A-1,~/pictures/wallpapers/minecraft-2.jpg
wallpaper = DP-1,~/pictures/wallpapers/minecraft-2.jpg