xwayland {
    force_zero_scaling = true # Force zero scaling for XWayland windows
}
# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
    force_split = 2
    split_bias = 1
    default_split_ratio = 1.2
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = slave
    mfact = 0.65
    allow_small_split = true
    drop_at_cursor = true
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc { 
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    vfr = true
    background_color = rgb(2e3440)

    animate_manual_resizes = false
    animate_mouse_windowdragging = false
    middle_click_paste = false

    focus_on_activate = true
}

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = true
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

##############
### Config ###
##############

$config = ~/.config/hypr/config
$hardware = ~/.config/hypr/hardware
source = $config/animation.conf
source = $config/apps.conf
source = $config/binds.conf
source = $config/env.conf
source = $config/exec.conf
source = $config/rules.conf
source = $config/style.conf
