
###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

$font = "MartianMono Nerd Font"
$terminal = kitty
$fileManager = nemo
$browser = zen-browser
$menu = /usr/bin/rofi -show drun -kb-cancel Escape -theme ~/.config/rofi/config.rasi
$lock = hyprctl dispatch dpms off
