
###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

$font = "MartianMono Nerd Font"
$terminal = ghostty
$fileManager = thunar
$browser = helium-browser
$altbrowser = zen-browser
$menu = /usr/bin/rofi -show drun -kb-cancel Escape -theme ~/.config/rofi/config.rasi
#$menu = qs ipc call toggleLauncher
$lock = hyprctl dispatch dpms off
$editor = ~/.local/bin/zed
$alteditor = cursor
