
# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    blur {
        enabled = false
        size = 3
        passes = 2

        vibrancy = 0.5
    }
}


windowrule = match:class ghostty, opacity 0.85
windowrule = match:class obsidian, opacity 0.85
windowrule = match:class discord, opacity 0.85,
windowrule = match:title Beeper, opacity 0.85
windowrule = match:class Spotify, opacity 0.85
windowrule = match:class Slack, opacity 0.85
