
# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    blur {
        enabled = true
        size = 3
        passes = 2
        
        vibrancy = 0.5
    }
}


windowrule = opacity 0.85,class:^(kitty)$
windowrule = opacity 0.85,class:^(obsidian)$
windowrule = opacity 0.85, class:^(discord)$
windowrule = opacity 0.85, class:^(BeeperTexts)$
windowrule = opacity 0.85,class:^(Spotify)$
