

################# 
### AUTOSTART ###
#################

# exec-once = $terminal
exec-once = powertop --auto-tune
exec-once = syncthing --no-browser
exec-once = ~/.config/quickshell/launchshell.sh
exec-once = systemctl start bluetooth.service
exec-once = nm-applet
exec-once = mako
exec-once = swww-daemon
exec-once = swayidle -w timeout 360 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on'
exec-once = spicetify backup apply
exec-once = betterdiscordctl reinstall

# exec apps
# exec-once = kitty
# exec-once = [workspace special:obsidian silent] obsidian

# themes
exec = gsettings set org.gnome.desktop.interface gtk-theme "Nordic"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface icon-theme "Zafiro-Nord-Black"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

# idr know what these do :)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
