

################# 
### AUTOSTART ###
#################

# exec-once = $terminal
exec-once = powertop --auto-tune
exec-once = syncthing --no-browser
exec-once = swayidle -w timeout 360 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on'
exec-once = ~/.config/quickshell/launchshell.sh
exec-once = systemctl start bluetooth.service
exec-once = nm-applet
exec-once = mako
exec-once = swww-daemon

exec = gsettings set org.gnome.desktop.interface gtk-theme "Nordic"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface icon-theme "Zafiro-Nord-Black"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

