
##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrulev2 = tile, class:^(kitty)$
windowrule = opacity 0.9,class:^(kitty)$
windowrulev2 = float, class:^(nemo)$
windowrulev2 = size 800 600, class:^(nemo)$

windowrule = opacity 0.9,class:^(obsidian)$
windowrule = opacity 0.95,class:^(code)$