
##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrulev2 = tile, class:^($terminal)$
windowrulev2 = float, class:^($fileManager)$
windowrulev2 = size 800 600, class:^($fileManager)$

# Make XDG file picker/chooser dialogs float
windowrulev2 = float, class:^(xdg-desktop-portal-gtk)$
windowrulev2 = size 800 600, class:^(xdg-desktop-portal-gtk)$

# windowrule = opacity 0.9,class:^(kitty)$
# windowrule = opacity 0.9,class:^(obsidian)$
# windowrule = opacity 0.9, class:^(discord)$
# windowrule = opacity 0.85, class:^(BeeperTexts)$
# windowrule = opacity 0.9,class:^(spotify)$
# windowrule = opacity 0.9, class:^(Slack)$
