
##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrulev2 = tile, class:^(kitty)$
windowrulev2 = float, class:^(nemo)$
windowrulev2 = size 800 600, class:^(nemo)$

windowrule = opacity 0.9,class:^(kitty)$
windowrule = opacity 0.9,class:^(obsidian)$
windowrule = opacity 0.9, class:^(discord)$
windowrule = opacity 0.85, class:^(BeeperTexts)$
windowrule = opacity 0.9,class:^(Spotify)$

workspace = special:texts
workspace = special:obsidian
workspace = special:music
workspace = special:browser

windowrulev2 = workspace special:texts, class:^(Beeper)$
windowrulev2 = workspace special:texts, class:^(slack)$
windowrulev2 = workspace special:texts silent, class:^(discord)$
# windowrulev2 = workspace special:browser, class:^(zen)$
windowrulev2 = workspace special:browser, class:^(firefox)$
windowrulev2 = workspace special:music, class:^(spotify)$
windowrulev2 = workspace special:obsidian silent, class:^(obsidian)$

