
# Refer to https://wiki.hyprland.org/Configuring/Variables/
# https://wiki.hyprland.org/Configuring/Variables/#general
general { 
    gaps_in = 4
    gaps_out = 15

    border_size = 3


    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgb(81a1c1)
    col.inactive_border = rgba(434C5Eff)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = master

}


# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 10

    # Change transparency of focused and unfocused windows
    active_opacity = 1
    inactive_opacity = 0.9
    dim_special = 0.2

#    drop_shadow = true
#    shadow_range = 4
#    shadow_render_power = 3
#    col.shadow = rgba(1a1a1aee)
    shadow {
	    enabled = false
    }
    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = false
        size = 20
        passes = 1
        
        vibrancy = 0.1696
    }
}